In [13]:
import pandas as pd


noms_colonnes = ["sequence name", "frame number", "label", "HeightWidthRatio", "MajorMinorRatio", "BoundingBoxOccupancy", "MaxStdXZ", "HHmaxRatio", "H", "D", "P40"]  # Remplacez-les par les noms réels de vos colonnes

df = pd.read_csv(r'C:\Users\ludovic.souquet\Documents\GitHub\ludovic.souquet\Exercice_moustafa\URFD_Dataset.csv', names=noms_colonnes)
df.head(10)

,sequence name,frame number,label,HeightWidthRatio,MajorMinorRatio,BoundingBoxOccupancy,MaxStdXZ,HHmaxRatio,H,D,P40
0,fall-01,1,-1,3.1667,2.9098,0.55367,126.0258,1.03240,1899.5366,1055.9988,0.047310
1,fall-01,2,-1,3.3067,2.9699,0.47876,125.5657,1.12510,2070.1193,1065.9506,0.048175
2,fall-01,3,-1,3.1408,3.0506,0.54374,123.1570,1.01610,1869.6442,1055.4955,0.050180
3,fall-01,4,-1,3.4306,3.1435,0.48859,124.5614,1.12510,2070.1193,1076.1464,0.047877
4,fall-01,5,-1,3.6324,3.3012,0.49744,123.6089,1.12510,2070.1193,1075.5053,0.052543
5,fall-01,6,-1,3.3788,3.4746,0.54308,121.8830,1.01740,1872.0175,1065.8971,0.054923
6,fall-01,7,-1,3.3636,3.5179,0.52355,122.4290,0.98797,1817.8588,1076.0167,0.059575
7,fall-01,8,-1,3.1739,3.2962,0.48442,123.8245,0.97907,1801.4878,1074.7731,0.047814
8,fall-01,9,-1,3.4531,3.4923,0.50834,123.5248,0.97907,1801.4878,1067.8731,0.051043
9,fall-01,10,-1,3.6618,3.4449,0.43710,127.3268,1.12510,2070.1193,1090.5386,0.043643

### Récupérez la première valeur de la colonne
premiere_valeur = df[nom_colonne].iloc[0]